### PR TITLE
[Proposal] Rename to RethinkDB

### PR DESCRIPTION
**Pull request by scrogson**
@hamiltop, fantastic start to this library. Was wondering if you'd
consider renaming from Exrethinkdb to RethinkDB.

IMHO it looks more legit :wink:

### CODE REVIEW

**Comment by hamiltop** [comment]
I went with `Exrethinkdb` to make it distinct from https://github.com/azukiapp/elixir-rethinkdb

According to https://github.com/azukiapp/elixir-rethinkdb/issues/12 it's basically abandoned, which is what prompted me to start `Exrethinkdb`. I'd prefer not to take over the name `RethinkDB` without @azukiapp giving a go ahead (meaning `elixir-rethinkdb` is done, and this repo would be considered its successor).

**Comment by hamiltop** [comment]
See https://github.com/azukiapp/elixir-rethinkdb/issues/12 for full context. We should be good to go with the rename. I've done a lot of work recently so we will need to update the new files as well.

I'll check this branch out and make the switch ASAP. The longer we wait, the greater the chance we break someones code.

**Comment by nurugger07** [comment]
Probably a good idea before people start contributing too :)

**Comment by hamiltop** [comment]
Should we rename the repo to `rethinkdb-elixir` or leave it as `exrethinkdb`?

**Comment by scrogson** [comment]
I like `rethinkdb-elixir` or `rethinkdb.ex`

**Comment by scrogson** [comment]
Bummer...I just rebased everything

**Comment by hamiltop** [comment]
@scrogson Just as you updated your branch, I did the search and replace myself and pushed. The only difference is `rethinkd_db` vs `rethinkdb`. The latter is what the official ruby driver does:

```
require 'rethinkdb'
include RethinkDB::Shortcuts
```

I think that's the correct pattern.

Sorry about the rebase issue.

**Comment by hamiltop** [comment]
@scrogson Please add your name to CONTRIBUTORS.md I want to at least get you some recognition for helping out.

**Pull request closed without merging**
